package com.ray.router.processor.utils;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.WildcardTypeName;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;

/**
 * Some consts used in processors
 *
 * @author Alex <a href="mailto:zhilong.liu@aliyun.com">Contact me.</a>
 * @version 1.0
 * @since 16/8/24 20:18
 */
public class Consts {
    // Generate
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "Router";
    public static final String TAG = PROJECT + "::";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY ROUTER.";
    public static final String METHOD_LOAD_INTO = "loadInto";
    public static final String METHOD_INJECT = "inject";
    public static final String NAME_OF_ROOT = PROJECT + SEPARATOR + "Root";
    public static final String NAME_OF_PROVIDER = PROJECT + SEPARATOR + "Providers";
    public static final String NAME_OF_GROUP = PROJECT + SEPARATOR + "Group" + SEPARATOR;
    public static final String NAME_OF_INTERCEPTOR = PROJECT + SEPARATOR + "Interceptors";
    public static final String NAME_OF_AUTOWIRED = SEPARATOR + PROJECT + SEPARATOR + "Autowired";
    public static final String NAME_OF_SERVICE_IMPL = SEPARATOR + "Impl";
    public static final String PACKAGE_OF_GENERATE_FILE = "com.alibaba.android.arouter.routes";

    // System interface
    public static final String ACTIVITY = "android.app.Activity";
    public static final String FRAGMENT = "android.app.Fragment";
    public static final String FRAGMENT_V4 = "android.support.v4.app.Fragment";
    public static final String SERVICE = "android.app.Service";
    public static final String PARCELABLE = "android.os.Parcelable";
    public static final String BUNDLE = "android.os.Bundle";

    // Java type
    private static final String LANG = "java.lang";
    public static final String BYTE = LANG + ".Byte";
    public static final String SHORT = LANG + ".Short";
    public static final String INTEGER = LANG + ".Integer";
    public static final String LONG = LANG + ".Long";
    public static final String FLOAT = LANG + ".Float";
    public static final String DOUBEL = LANG + ".Double";
    public static final String BOOLEAN = LANG + ".Boolean";
    public static final String STRING = LANG + ".String";

    // Custom interface
    private static final String FACADE_PACKAGE = "com.ray.router.facade";
    private static final String ANNOTATION_PACKAGE = "com.ray.router";
    public static final String ISYRINGE = FACADE_PACKAGE + ".ISyringe";
    public static final String IACTION = FACADE_PACKAGE + ".action.IAction";

    // Log
    static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler ";

    // Options of processor
    public static final String KEY_MODULE_NAME = "moduleName";

    // Annotation type
    public static final String ANNOTATION_TYPE_INTECEPTOR = ANNOTATION_PACKAGE + ".annotation.Interceptor";
    public static final String ANNOTATION_TYPE_ROUTE = ANNOTATION_PACKAGE + ".annotation.Route";
    public static final String ANNOTATION_TYPE_AUTOWIRED = ANNOTATION_PACKAGE + ".annotation.Autowired";

    //Method
    public static final String METHOD_ROOT_INTERCEPTOR = "rootInterceptors";
    public static final String METHOD_INTERCEPTOR = "interceptors";
    public static final String METHOD_MATCH_INTERCEPTOR = "matchInterceptors";
    public static final String METHOD_ACTION = "actions";
    public static final String METHOD_ACTION_INPUT_CLZ = "actionInputClzs";
    public static final String METHOD_CREATE_INTENT = "createIntent";
    public static final String METHOD_INVOKE = "invoke";
    public static final String METHOD_CANCEL = "cancel";


    public static final ClassName CLASS_ACTION = ClassName.get("com.ray.router.facade.action", "IAction");
    public static final ClassName CLASS_ACTION_ACTIVITY = ClassName.get("com.ray.router.facade.action", "ActivityAction");
    public static final ClassName CLASS_ACTION_FRAGMENT = ClassName.get("com.ray.router.facade.action", "FragmentAction");
    public static final ClassName CLASS_ACTION_FRAGMENT_V4 = ClassName.get("com.ray.router.facade.action", "FragmentActionV4");
    public static final ClassName CLASS_INTERCEPTOR = ClassName.get("com.ray.router.facade", "IInterceptor");
    public static final ClassName CLASS_PROVIDER = ClassName.get("com.ray.router.facade", "Provider");
    public static final ClassName CLASS_INTENT = ClassName.get("android.content", "Intent");
    public static final ClassName CLASS_CONTEXT = ClassName.get("android.content", "Context");
    public static final ClassName CLASS_FRAGMENT = ClassName.get("android.app", "Fragment");
    public static final ClassName CLASS_FRAGMENT_V4 = ClassName.get("android.support.v4.app", "Fragment");
    public static final ClassName CLASS_BUNDLE = ClassName.get("android.os", "Bundle");
    public static final ClassName CLASS_REQUEST = ClassName.get("com.ray.router.facade.data", "Request");
    public static final ClassName CLASS_RESPONSE = ClassName.get("com.ray.router.facade.data", "Response");
    public static final ClassName CLASS_ACTION_CALLBACK = ClassName.get("com.ray.router.facade.callback", "IActionResultCallback");
    public static final ClassName CLASS_ROUTER = ClassName.get("com.ray.router.launcher", "Router");
    public static final ClassName CLASS_CALL = ClassName.get("com.ray.router.facade", "Call");
    public static final ClassName CLASS_RX_OBSERVABLE = ClassName.get("io.reactivex", "Observable");
    public static final ClassName CLASS_ROUTER_RX = ClassName.get("com.ray.router.rx", "RouterRx");

    //泛型参数类型
    //Class<? extends IAction>
    public static final ParameterizedTypeName CLASS_CLZ_EXTENDS_ACTION =
            ParameterizedTypeName.get(ClassName.get(Class.class), WildcardTypeName.subtypeOf(CLASS_ACTION));
    //Class<? extends IInterceptor>
    public static final ParameterizedTypeName CLASS_CLZ_EXTENDS_INTERCEPTOR =
            ParameterizedTypeName.get(ClassName.get(Class.class), WildcardTypeName.subtypeOf(CLASS_INTERCEPTOR));
    //Collection<IInterceptor>
    public static final ParameterizedTypeName CLASS_COLLECTION_INTERCEPTOR =
            ParameterizedTypeName.get(ClassName.get(Collection.class), CLASS_INTERCEPTOR);
    //Collection<Class<? extends IInterceptor>>
    public static final ParameterizedTypeName CLASS_COLLECTION_CLZ_EXTENDS_INTERCEPTOR =
            ParameterizedTypeName.get(ClassName.get(Collection.class), CLASS_CLZ_EXTENDS_INTERCEPTOR);
    //ArrayList<IInterceptor>
    public static final ParameterizedTypeName CLASS_LIST_INTERCEPTOR =
            ParameterizedTypeName.get(ClassName.get(ArrayList.class), CLASS_INTERCEPTOR);
    //ArrayList<Class<? extends IInterceptor>>
    public static final ParameterizedTypeName CLASS_LIST_CLZ_EXTENDS_INTERCEPTOR =
            ParameterizedTypeName.get(ClassName.get(ArrayList.class), CLASS_CLZ_EXTENDS_INTERCEPTOR);
    //HashMap<String, Collection<Class<? extends IInterceptor>> >
    public static final ParameterizedTypeName CLASS_MAP_STRING_COLLECTION_CLZ_EXTENDS_INTERCEPTOR =
            ParameterizedTypeName.get(ClassName.get(HashMap.class), ClassName.get(String.class), CLASS_COLLECTION_CLZ_EXTENDS_INTERCEPTOR);
    //HashMap<String, IAction>
    public static final ParameterizedTypeName CLASS_MAP_STRING_ACTION =
            ParameterizedTypeName.get(ClassName.get(HashMap.class), ClassName.get(String.class), CLASS_ACTION);
    //HashMap<String, Class<? extends IAction>>
    public static final ParameterizedTypeName CLASS_MAP_STRING_CLZ_EXTENDS_ACTION =
            ParameterizedTypeName.get(ClassName.get(HashMap.class), ClassName.get(String.class), CLASS_CLZ_EXTENDS_ACTION);
    //Map<Class<? extends IAction>, Class>
    public static final ParameterizedTypeName CLASS_MAP_CLZ_EXTENDS_ACTION_CLZ =
            ParameterizedTypeName.get(ClassName.get(HashMap.class), CLASS_CLZ_EXTENDS_ACTION, ClassName.get(Class.class));;
    public static final ParameterizedTypeName CLASS_REQUEST_BUNDLE =
            ParameterizedTypeName.get(CLASS_REQUEST, CLASS_BUNDLE);
    public static final ParameterizedTypeName CLASS_ACTION_RESULT_CALLBACK_FRAGMENT =
            ParameterizedTypeName.get(CLASS_ACTION_CALLBACK, CLASS_FRAGMENT);
    public static final ParameterizedTypeName CLASS_ACTION_RESULT_CALLBACK_FRAGMENT_V4 =
            ParameterizedTypeName.get(CLASS_ACTION_CALLBACK, CLASS_FRAGMENT_V4);
}